### ISSUE TITLE
Implicit id for Router

### ISSUE THREAD

**Issue by zsoltk** [zsoltk/compose-router#1]
Right now Router needs an explicit unique id for back stack store/retrieval from parent. It would be nice to make this implicitly without having to ask client code to define id.

**Comment by mvarnagiris** [comment]
So if you assume that users will use different `sealed class` per `Router`, then you could do something like this:
```
@Composable
inline fun <reified T: Any> Router(defaultRouting: T, children: @Composable() (BackStack<T>) -> Unit) {
    val contextId = T::class.java.name
    ...
}
```
Or
```
@Composable
inline fun <reified T: Any> Router(defaultRouting: T, contextId: String = T::class.java.name, children: @Composable() (BackStack<T>) -> Unit) {
    ...
}
```

**Comment by zsoltk** [comment]
That's a great idea, thanks! Opened #8 for it if you'd like to review.

**Comment by mvarnagiris** [comment]
Looks good!
