### ISSUE TITLE
Unable to import when built with com.android.tools.build:gradle > 4.1.0-alpha05 

### ISSUE THREAD

**Issue by luca992** [zsoltk/compose-router#22]
I mentioned this bug in https://github.com/zsoltk/compose-router/pull/21. Probably needs to be reported to Google. It still does not work with 4.1.0-alpha09.

For some reason with com.android.tools.build:gradle versions 4.1.0-alpha06 - 4.1.0-alpha08 the META-INF folder isn't added to the classes.jar in the .aar outputs

![Screenshot from 2020-05-11 16-30-42](https://user-images.githubusercontent.com/4157455/81621960-9ca1f200-93a4-11ea-853b-3bd0f5d955f9.png)

![Screenshot from 2020-05-11 16-26-20](https://user-images.githubusercontent.com/4157455/81621966-9e6bb580-93a4-11ea-8f95-752bd266ddea.png)

My branch built with `com.android.tools.build:gradle:4.1.0-alpha05` includes the  META-INF folder and I can successfully build my project
![Screenshot from 2020-05-11 16-27-40](https://user-images.githubusercontent.com/4157455/81621965-9dd31f00-93a4-11ea-99da-99f186ccddb9.png)

**Comment by WebTiger89** [comment]
Same for me. With version 0.9.0 I did not have this problem.

**Comment by zsoltk** [comment]
Fixed in #24 , released as tag 0.11.1. Seems to be working for me. Let me know if you have any further issues.

**Comment by WebTiger89** [comment]
Thanks man. Works for me!
