### ISSUE TITLE
Top of Stack

### ISSUE THREAD

**Issue by notquiteamonad** [zsoltk/compose-router#29]
Hi,

I'd find it really useful to know what the top item in the backstack is - I'm using bottom navigation and knowing the top item on the backstack would help in deciding which item at the bottom should be highlighted (even when a few destinations deep in that stack).

Is there a reason this shouldn't be exposed?

**Comment by notquiteamonad** [comment]
I'll put in a PR in case you deem it to be a reasonable thing to do.

**Comment by notquiteamonad** [comment]
Thinking about this I wonder if it'd be better using a name like `first` or last instead - given the top of the stack is usually the last item. I was thinking more in terms of top-level destination.

**Comment by zsoltk** [comment]
Hey @samueldple , I don't think this is the right way to approach it. 

The `last` element should be deciding what you show as "selected". Using the oldest element in the history for what you want makes it purely accidental.

What I think you want (correct me if I'm wrong), is a kind of a hierarchy, where you have top-level navigation destinations (deciding the highlighted menu item), but also screens "deeper" inside them. 

In this case you shouldn't map this hierarchy as something flat with only one `Router`. The idea is to have a nested hierarchy, with as many `Router`s as levels in this hierarchy, each with their own back stack. This way you can use the last element in the top-level back stack for highlighting menu items. Have a look at `app-lifelike` which shows this pattern.

PS: I agree naming feels off, "top" should definitely be the most recent element in a stack

**Comment by notquiteamonad** [comment]
Thanks @zsoltk, that sounds reasonable. I'll take a look at `app-lifelike`

**Comment by notquiteamonad** [comment]
Having taken a look at that it seems like exactly what you want, so I guess this isn't needed.

Feel free to close this and the associated PR if you think they're not needed :smile:
