### ISSUE TITLE
Off by one error in replace

### ISSUE THREAD

**Issue by notquiteamonad** [zsoltk/compose-router#31]
My understanding of the `replace` function on `BackStack` is that it should swap the item at the top of the stack, so if the routing is `a,b,c` and `replace(d)` is called it should become `a,b,d`.

However, the replace function uses `.subList(0, elements.lastIndex - 1)` which removes 2 elements (the second argument being exclusive).

This should probably either change to use `size` or remove the `-1` (the latter makes more sense to me).

This is, of course, all invalid if I've misunderstood what replace is supposed to do.

**Comment by zsoltk** [comment]
Thanks @samueldple! Released fix as 0.13.1
