### ISSUE TITLE
[Proposal] Expose read access for BackStack#elements

### ISSUE THREAD

**Issue by friendoye** [zsoltk/compose-router#34]
I wonder if there is any way to retrieve all elements from `BackStack`?
It can be useful in the following cases:
1) We want to render all screens from `BackStack` on top of each other, so after navigating back we will not re-render some screens.
2) Integration with [compose-backstack](https://github.com/zach-klippenstein/compose-backstack) (library for rendering animated transitions between backstacks of screens) would be much simpler, because nowadays it requires list of screens as one of args to its `Composable`. There are some workarounds, such as using Kotlin Reflection or using `state/remember` for maintaining backstack yourself, but it would be great to have read access directly to `BackStack#elements`.

@zsoltk WDYT?

**Comment by zsoltk** [comment]
I don't see why not. As a short term fix, it will do. Feel free to submit a PR.

Otherwise an abstraction over the back stack is on the way to address a more general case. That should also allow for keeping more than one element alive, among other things.

**Comment by friendoye** [comment]
Sounds great, will look forward to new abstraction!

**Comment by friendoye** [comment]
Closed by #37.
