### ISSUE TITLE
[Question] Integration with ViewModelStore? 

### ISSUE THREAD

**Issue by R4md4c** [zsoltk/compose-router#40]
I'm wondering if it's possible to adapt compose-router to be able to scope AndroidX ViewModel to a `Backstack` element? 

For example, as long as the route is still in the backstack then the ViewModel is kept alive, and once the route is popped ViewModel's `onCleared()` gets called.

**Comment by CarsonRedeye** [comment]
Why is this closed? I'm curious too.
