### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by noe** [zsoltk/compose-router#51]
compose-router does not specify an open source license. This implies, [as it is generally understood](https://opensource.stackexchange.com/q/1720/22146), that [it cannot be assumed to be open source](https://opensource.stackexchange.com/q/1150/22146).

@zsoltk could you please clarify this matter and, if compose-router is indeed meant to be open-source, could you add a license file?

**Comment by zsoltk** [comment]
Added. Thanks for spotting!
